export const skillsJson = {
	Soft: [
		"Teamwork",
		"Problem-solving",
		"Communication",
		"Adaptability",
		"Time Management",
		"Leadership",
		"Critical Thinking",
	],
	Engineering: [
		"Git",
		"Vercel",
		"Notion",
		"Figma",
		"VS Code",
		"IntelliJ IDEA",
		"Jira",
		"Confluence",
		"Postman",
		"Bruno",
		"Agile",
		"Scrum",
		"Docker",
		"Windows",
		"Linux",
	],
	Software: ["C++", "C#", ".Net", "Python", "Delphi"],
	Web: [
		"HTML",
		"CSS",
		"JavaScript",
		"TypeScript",
		"React",
		"Next.js",
		"Node.js",
	],
	Database: ["MySQL", "SQL Server", "PostGreSQL", "MongoDB"],
};
